#!/usr/bin/env bash

_MY_FAST_FILE_DIR=${HOME}/.fast_file

emacs_fast_file_load ()
{
    local t_file=${t_dir}/${2}
    if ! emacsclient -n $t_file; then
        emacs $t_file
    fi
}

_ff_home_folder_completion ()
{
    t_dir=${HOME}
    local cur="${COMP_WORDS[COMP_CWORD]}"

    COMPREPLY=( $(compgen -W '$(command ls -1A $t_dir)' -- $cur) )
}


_fast_file_dir_completion ()
{
    t_dir=$_MY_FAST_FILE_DIR
    local cur="${COMP_WORDS[COMP_CWORD]}"

    COMPREPLY=( $(compgen -W '$(command ls -1A $t_dir)' -- $cur) )
}


_fast_file_completion ()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "$prev" in
        -f)
            _fast_file_dir_completion
            return
            ;;
        -h)
            _ff_home_folder_completion
            return
            ;;
    esac

    COMPREPLY=( $(compgen -W '-f -h') -- $cur)
}

complete -F _fast_file_completion emacs_fast_file
